# Código funcao criacao de Matriz Mudança de Base

In [24]:
import numpy as np
import matplotlib.pyplot as plt

In [29]:
# Bases R3
A = [[1, 0, 1], [1, 1, 1], [1, 1, 2]]
B = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

"""
Explicação:

Para mais detalhes verificar documento: 2021-10-04-Mudanca-de-base.xopp
"""

def gen_M_A_to_B (A, B):
    a = np.array (A)
    b = np.array (B)

    # np.array([np.linalg.solve(a.T, a_row) for a_row in a]).T
    return np.linalg.solve(a, b)


In [41]:
# Teste função para criação de matriz mudanca de base com bases B1 e B2
b = [1, 2, 3] # Vetor na base B (canonica)

print(gen_M_A_to_B(A, B))               # Matriz de mudança de base A para B

print(np.matmul(gen_M_A_to_B(A, B), A)) # Matriz de mudança de base A para B. Multiplicação de matriz com a base A deve retornar a base B

a = np.matmul(gen_M_A_to_B(A, B), b)    # a = M_A_B * b
print(a)

[[ 1.  1. -1.]
 [-1.  1.  0.]
 [ 0. -1.  1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0. 1. 1.]
